"""The manual answer key loader, validator, and absent-file behaviour.

These test the *machinery* around the externally-authored file. They never assert its
contents — the file is the one piece of ground truth in this repository that
tooling must not author, complete, or correct.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from pydantic import ValidationError

from src.evals.manual_key import (
    SCHEMA_PATH,
    ManualAnswerKey,
    MissingManualKeyError,
    cross_reference_errors,
    json_schema,
    load_manual_key,
    manual_key_exists,
)

FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"


def _key(**overrides: Any) -> dict[str, Any]:
    base: dict[str, Any] = {
        "source_document": "fixtures/golden_rfp.pdf",
        "rfp_reference": "RFP-2026-MIG-014",
        "issuer": "Meridian Insurance Group",
        "deadline": "2026-07-15",
        "authored_by": "test",
        "authored_on": "2026-08-10",
        "questions": [
            {
                "order": 0,
                "number": "1.1",
                "section": "Company",
                "text": "Describe the team model.",
                "mandatory": True,
                "word_limit": None,
            },
            {
                "order": 1,
                "number": "1.2",
                "section": "Company",
                "text": "Where are your delivery centres?",
                "mandatory": False,
                "word_limit": 250,
            },
        ],
    }
    base.update(overrides)
    return base


@pytest.fixture(scope="module")
def pairs() -> list[dict[str, Any]]:
    with (FIXTURES / "qa_pairs.json").open(encoding="utf-8") as handle:
        data: list[dict[str, Any]] = json.load(handle)
    return data


class TestAbsentFile:
    def test_loading_raises_an_actionable_error(self, tmp_path: Path) -> None:
        with pytest.raises(MissingManualKeyError) as exc:
            load_manual_key(tmp_path / "nope.json")
        message = str(exc.value)
        assert "manual key missing — see §4" in message
        # The message wraps, so match on phrases that cannot straddle a newline.
        assert "generated by tooling" in message
        assert "externally authored" in message
        assert "make validate-manual-key" in message

    def test_existence_can_be_checked_without_raising(self, tmp_path: Path) -> None:
        """The harness reports a skipped category rather than crashing."""
        assert manual_key_exists(tmp_path / "nope.json") is False


class TestStructure:
    def test_a_well_formed_key_loads(self, tmp_path: Path) -> None:
        path = tmp_path / "key.json"
        path.write_text(json.dumps(_key()), encoding="utf-8")
        key = load_manual_key(path)
        assert len(key.questions) == 2
        assert key.in_document_order()[0].number == "1.1"

    def test_orders_must_be_gapless(self) -> None:
        payload = _key()
        payload["questions"][1]["order"] = 5
        with pytest.raises(ValidationError, match="with no gaps"):
            ManualAnswerKey.model_validate(payload)

    def test_orders_must_be_unique(self) -> None:
        payload = _key()
        payload["questions"][1]["order"] = 0
        with pytest.raises(ValidationError, match="duplicate"):
            ManualAnswerKey.model_validate(payload)

    def test_numbers_must_be_unique(self) -> None:
        payload = _key()
        payload["questions"][1]["number"] = "1.1"
        with pytest.raises(ValidationError, match="duplicate question"):
            ManualAnswerKey.model_validate(payload)

    def test_unknown_fields_are_refused(self) -> None:
        """A typo'd field would otherwise be silently ignored."""
        payload = _key()
        payload["questions"][0]["mandotory"] = True
        with pytest.raises(ValidationError):
            ManualAnswerKey.model_validate(payload)

    def test_a_zero_word_limit_is_refused(self) -> None:
        payload = _key()
        payload["questions"][0]["word_limit"] = 0
        with pytest.raises(ValidationError):
            ManualAnswerKey.model_validate(payload)

    def test_wrapped_text_is_normalised(self) -> None:
        """PDF line wrapping must not read as a disagreement with the extractor."""
        payload = _key()
        payload["questions"][0]["text"] = "Describe   the\n  team   model."
        key = ManualAnswerKey.model_validate(payload)
        assert key.in_document_order()[0].text == "Describe the team model."


class TestCrossReferences:
    def test_a_real_live_answer_id_passes(self, pairs: list[dict[str, Any]]) -> None:
        live = next(p for p in pairs if not p["superseded_by"])
        payload = _key()
        payload["questions"][0]["expected_best_match_answer_id"] = live["answer_id"]
        assert cross_reference_errors(ManualAnswerKey.model_validate(payload), pairs) == []

    def test_an_unknown_answer_id_is_reported(self, pairs: list[dict[str, Any]]) -> None:
        payload = _key()
        payload["questions"][0]["expected_best_match_answer_id"] = "ANS-9999"
        errors = cross_reference_errors(ManualAnswerKey.model_validate(payload), pairs)
        assert len(errors) == 1
        assert "not in the corpus" in errors[0]

    def test_a_superseded_answer_id_is_reported(self, pairs: list[dict[str, Any]]) -> None:
        """Expecting a superseded answer would contradict the staleness eval."""
        stale = next(p for p in pairs if p["superseded_by"])
        payload = _key()
        payload["questions"][0]["expected_best_match_answer_id"] = stale["answer_id"]
        errors = cross_reference_errors(ManualAnswerKey.model_validate(payload), pairs)
        assert len(errors) == 1
        assert "superseded" in errors[0]

    def test_questions_without_an_expected_match_are_fine(
        self, pairs: list[dict[str, Any]]
    ) -> None:
        """The key is primarily about extraction; matches are optional."""
        assert cross_reference_errors(ManualAnswerKey.model_validate(_key()), pairs) == []


class TestSchemaFile:
    def test_the_committed_schema_matches_the_model(self) -> None:
        """Regenerate with: python -m scripts.validate_manual_key --emit-schema"""
        assert SCHEMA_PATH.is_file(), "the schema file must be committed"
        committed = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
        assert committed == json_schema()

    def test_the_schema_documents_its_independence(self) -> None:
        description = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))["description"]
        assert "Externally-authored" in description
        assert "independent of the" in description
        assert "Never generated or edited by the builder" in description


class TestTheCommittedKey:
    """The shipped key, checked for the properties the evals depend on.

    Its *contents* are never asserted against expected values — that would make
    the builder the arbiter of the ground truth it is being measured against.
    These check shape and provenance only.
    """

    def test_it_is_committed(self) -> None:
        assert manual_key_exists(), "the extraction evals cannot run without it"

    def test_it_names_its_author_and_source(self) -> None:
        """A key written against an older rendering must be identifiable."""
        key = load_manual_key()
        assert key.authored_by
        assert key.source_document == "fixtures/golden_rfp.pdf"
        assert key.authored_on

    def test_it_declares_its_independence(self) -> None:
        """The invariant is independence from the pipeline and the fixture source."""
        provenance = load_manual_key().authored_by.casefold()
        assert "golden_rfp_source" not in provenance or "not from" in provenance

    def test_it_cross_references_cleanly(self) -> None:
        with (FIXTURES / "qa_pairs.json").open(encoding="utf-8") as handle:
            pairs = json.load(handle)
        assert cross_reference_errors(load_manual_key(), pairs) == []

    def test_no_expected_match_is_superseded(self) -> None:
        """Retrieval must surface replacements; the staleness eval allows zero."""
        with (FIXTURES / "qa_pairs.json").open(encoding="utf-8") as handle:
            pairs = json.load(handle)
        superseded = {p["answer_id"] for p in pairs if p["superseded_by"]}
        expected = {
            q.expected_best_match_answer_id
            for q in load_manual_key().questions
            if q.expected_best_match_answer_id
        }
        assert expected & superseded == set()
